name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-wakatime-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LOCALE: "en"
          MODE: "weekly" 
          AWAIT_JOB: "true"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update WakaTime stats in README"
          add: "README.md"
